### ISSUE TITLE
Make it possible to save/restore cursor position

### ISSUE THREAD

**Issue by yshui** [mawww/kakoune#2219]
This is mentioned in #74, and I think it is a good idea to do this in a hook. However, current it is hard to do this efficiently.

There are 2 problems:

* BufClose is fired to late. In a BufClose hook, kak_cursor_{line, column} is always 1. Meaning we would have to track cursor movement all the time, because we don't know when the buffer will be closed.
* There is no simple way to track buffer changes. In order to support the scenario where the user close a modified buffer without saving it, we need to know the cursor position in most recent "clean" buffer, to do that efficiently, we need to track buffer changes, i.e. a hook that triggers when the content of the buffer is changed by any means.

**Comment by mawww** [comment]
One thing is that BufClose might run from any context, and we might have multiple clients displaying the same buffer (hence different set of selections on the same buffers active). My understanding is that kakoune-state-save will save the value from the last window that saw a NormalIdle hook getting called, which might be good enough for many cases.

**Comment by Screwtapello** [comment]
Yes, if you have the same buffer open in multiple windows, you have multiple (sets of) selections, and there's no way to know which set you'll expect to find the next time you open that file. Since there's no "right" answer, kakoune-state-save leaves it as implementation-defined, which happens to be "the state of the last window to see a NormalIdle event".

**Comment by mawww** [comment]
Yep, I think that means we resolve this issue ?

**Comment by Screwtapello** [comment]
Fine by me!

**Comment by yshui** [comment]
@mawww This is alright. But I think using `NormalIdle` for this is not will efficient.

**Comment by mawww** [comment]
NormalIdle along with checking `$kak_timestamp` is the preferred way to check for buffer modifications at the moment.

**Comment by Screwtapello** [comment]
I've updated my plugin so that the `NormalIdle` hook only copies the selection data to a buffer-scoped option, instead of writing directly to disk. It still has to invoke a shell because it needs an `if` statement, but that's probably about as efficient as it can be unless Kakoune adds a special `NormalIdleWithoutUnsavedChanges` hook. ;)

**Comment by yshui** [comment]
@Screwtapello @mawww It would be nice to have a `BufDirty` hook.

**Comment by yshui** [comment]
@Screwtapello @mawww It'd be nice to have a `BufDirty` hook.

Also my impression is that `BufClose` happens when the last window is gone? It would be nice if we can still get a cursor location in `BufClose` hook.

**Comment by Screwtapello** [comment]
In Kakoune, cursors are fundamentally part of a Window rather than a Buffer, so `BufClose` can never have cursor locations available. Besides which, as you pointed out in your original post, you need to store the cursor state immediately before the last unsaved changes, rather than at the time the buffer is closed. BufClose will never be able to reach back that far.

**Comment by mawww** [comment]
Regarding `BufClose`, the problem is that there is no guarantees what event would trigger it, it could be called from a command run from a specific client, in which case it could (but not necessarily) make sense to run it in that client context, with a window (and hence some selections) available, but it could as well run from many other contexts, like another hook triggering a buffer deletion, or a command comming from another process through `echo 'commands...' | kak -p my-session`... in which cases we dont have any set of selections available.
