### ISSUE TITLE
backspace merges contiguous selections during append

### ISSUE THREAD

**Issue by FlyingWombat** [mawww/kakoune#2861]
### Steps 
1. Place two cursors next to each other
2. Press `a` and insert some text
3. Press `<backspace>`

### Outcome 
One character will be deleted, and adjacent selections will merge together.

### Expected 
`<backspace>` should merely delete the last entered char in this case, without merging.  

### Notes
This seems to be an edge case for merging overlapping selections; it does not happen when inserting text using `i`. Here, the selections are only temporarily overlapping, by 1, as they are being extended by the append operation. Upon exiting insert mode, they are not overlapping, but adjacent.  
The current behavior is annoying when you happen to be appending to adjacent selections, as you effectively cannot backspace.

Tested on kakoune-git commit 06d4ee578e5955d3d444bbe9dd03285df958cdd1  
with -n option

**Comment by mawww** [comment]
Should be fixed, thanks for reporting that.

**Comment by andreyorst** [comment]
@mawww the issue still reproducible with:

    kak -n -e "execute-keys '%di<space><space><esc>ggLs.<ret>atext<esc>L'"

Happens exactly on <kbd>L</kbd> keypress. Doesn't happen in selections are not next to each other.

**Comment by FlyingWombat** [comment]
I looked into the issue with the two mentioned plugins. The problem is `L` as @andreyorst said.  
But, more specifically, the problem is that a hook, such as InsertDelete is entering executing keys in a "temporary normal" mode on top of the `insert` mode context. And there, `L` is merging the adjacent selections -- which is the expected behavior, normally, but a problem here.

So, perhaps a solution would be to avoid merging selections when "insert" mode is in the mode stack. Are there situations where we would want to merge selections in a 'temporary normal" mode on top of "insert" mode?

**Comment by andreyorst** [comment]
ah, now I see it. When we have two selections side by side and increasing them to the left it results into overlapping selections, that got merged, which is pretty logical.

    [a]{a}b
    # pressing L
    [a{a]b}
    # merging
    [aab]

I don't think we can do anything here but to change algorithm in smarttab to avoid `L`. I'll try to think about it.

**Comment by mawww** [comment]
(Did not read everything in detail, but this kind of behaviour is why `itersel` exists).

**Comment by andreyorst** [comment]
Yeah, I've thought about `itersel` too
