### ISSUE TITLE
Home and end keys are not working over ssh

### ISSUE THREAD

**Issue by shrit** [mawww/kakoune#3272]
Using Kakoune on Archlinux over ssh connections. It seems to me that both `home` and `end` keys are not working.
This behavior is expected whether using xterm or not.
Tested by using `kak -n `
`TERM=xterm-256color`

**Comment by Screwtapello** [comment]
What version of Kakoune are you using? #3252 is a similar-sounding issue that was fixed a few days ago, but is not yet in an official release.

**Comment by shrit** [comment]
hm, I see, The version I use is 10/12 I think

**Comment by shrit** [comment]
Well, I have fetched the last master version, it is still not working.

**Comment by Screwtapello** [comment]
Which terminal are you using locally? What is `$TERM` set to? Are you using `mosh` or `tmux`? What is `$TERM` set to at the remote end?

What does `infocmp -1x | egrep 'home|end'` print locally? At the remote end?

What does `hexdump -C` print when you press the Home and End keys (you may need to press Enter or Ctrl-D afterward, to make it print anything)?

**Comment by shrit** [comment]
These are the configurations on the local side
System: Arch Linux,
Terminal: st-terminal (suckless)
```
$TERM: st-256color
> infocmp -1x | egrep 'home|end'
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
        home=\E[H,
        kend=\E[4~,
        khome=\E[1~
```
When pressing `home` button:
```
·> hexdump -C
^[[H00000000  1b 5b 48                                          |.[H|
00000003
```
When pressing `end` button:
```
·> hexdump -C
^[[4~00000000  1b 5b 34 7e                                       |.[4~|
00000004
```
=====================================
On the server side, these are the following output:
System: Arch Linux
I do not use `mosh`, I connect directly using `OpenSSH` and then I attach to a `tmux` session
`$TERM: tmux-256color`
```
infocmp -1x | egrep 'home|end'
        home=\E[H,
        kend=\E[4~,
        khome=\E[1~,
```
When `home` key pressed:
```
hexdump -C
^[[1~00000000  1b 5b 31 7e                                       |.[1~|
00000004

```
When end key pressed:
```
hexdump -C
^[[4~
00000000  1b 5b 34 7e 0a                                    |.[4~.|
00000005
```

From this morning I have noticed that that home and end keys are working now at the server. this is very strange since it did not work yesterday after I modified the $TERM on the server-side, knowing that I have started a new session of `tmux` yesterday.

Also, I do not if this is normal, but there is a part of Kakoune that is killing my memory. The lsp server, for instance, has been copied hundreds of times, also there is something that eating the memory that I was not able to identify until this moment:
This is a screenshot of `htop`, also I was not able to run `htop` from inside `tmux` since no resource was available to start a new process: `fork failed: Resource temporarily unavailable`
![2019-12-25-192916_1366x768_scrot](https://user-images.githubusercontent.com/15039782/71449546-c2f52700-274e-11ea-9f15-5c69087dfe76.png)

Another screenshot for a running script not able to identify it yet.

![2019-12-25-194339_1366x768_scrot](https://user-images.githubusercontent.com/15039782/71449565-765e1b80-274f-11ea-8999-f9ba680f58a7.png)

Finally, I have to restart the machine, since it is extremely buggy, and not being able to write normal commands.

**Comment by Screwtapello** [comment]
I'm not sure why your home and end keys stopped working, but I'm glad to hear the problem resolved itself.

It sounds like kak-lsp is doing weird things and stacking up thousands of idle helpers. I'm not sure what the problem is there either, but kak-lsp isn't actually an official part of Kakoune. You should probably file an issue on the kak-lsp tracker for that.

**Comment by shrit** [comment]
I know about kak-lsp, I have also created an issue for this. However, I think part of it is related to the missed configuration file, and an internal bug. You can check of rmore details here: https://github.com/ul/kak-lsp/issues/271

**Comment by lenormf** [comment]
If the keys are working now, could we close this issue?
