### ISSUE TITLE
[BUG] Repeating an edit command with dot (.) doesn't work in some situations

### ISSUE THREAD

**Issue by schragge** [mawww/kakoune#5122]
### Version of Kakoune

v2023.08.05-248-g4101e181

### Reproducer

When solving the VimGolf challenge [Increment number for every 10 lines](https://www.vimgolf.com/challenges/608d040766cd0a0007f52b0d) and repeating the previous `A` with a dot (`.`) inside a macro:
```
j9JCCQA,<c-r>#<esc>kQ9qggQj9C.,Qqq<space>q
```
Another example is [maximun and minimun](https://www.vimgolf.com/challenges/50406e76badccf000200003b).

It's not a practical solution (that would be `%<a-s><a-!>jq min,max<ret>`), but anyway:
```
O0<esc><a-o>4330o<c-r>#<esc>
%Q<a-m>Zs\d+<ret>*
[p<a-.>s<ret><c-s>
,yza<space><space><esc>p<c-o>
yz..p.a<lt><gt><esc>kQ39q
<a-.>d%<a-s><a-t>]&e&<space>q
```

### Outcome

The dot command does nothing. In the second example, it works when defining the macro within `Q...Q`, but not when repeating it with `q`.

Introduced with https://github.com/mawww/kakoune/commit/dbe8528231f61717210f796c93c85b852b760b33

### Expectations

The dot command appends comma following by a number (1st example) resp. two spaces (2nd example)

### Additional information

Probably related to #5120

**Comment by mawww** [comment]
I think this should be fixed by 6598d7b1b2d4d69f805288384b72a076666ca5ca can you confirm ?

**Comment by schragge** [comment]
No, unfortunately,  that commit indeed fixed the crash, but didn't fix the dot problem. Moreover, I'm now seeing another strange behavior, perhaps unrelated: when selecting a series of numbers with `s\d+<ret>`, stand-alone zeros don't get selected. E.g.
```
c1 2 0 3<esc>xs\d<ret>
```
