### ISSUE TITLE
[BUG] `blame-jump-message` test failing on Arch Linux

### ISSUE THREAD

**Issue by clarfonthey** [mawww/kakoune#5285]
### Version of Kakoune

commit 28a82b0

### Reproducer

Building the `kakoune-git` package on Arch Linux fails to pass all the tests. In the actual source for the PKGBUILD, the git version of kakoune is built directly with `make` (without additional build flags) and the tests are run via `make test`.

### Outcome

This diff shows up when running the test:

```
        blame-jump-message
          - { "jsonrpc": "2.0", "method": "draw_status", "params": [[{ "face": { "fg": "black", "bg": "yellow", "underline": "default", "attributes": [] }, "contents": "2017-07-14 A U Thor \"Don't break on single quotes or unbalanced {\"" }], [{ "face": { "fg": "default", "bg": "default", "underline": "default", "attributes": [] }, "contents": "*git* 13:2 " }, { "face": { "fg": "black", "bg": "yellow", "underline": "default", "attributes": [] }, "contents": "[scratch]" }, { "face": { "fg": "default", "bg": "default", "underline": "default", "attributes": [] }, "contents": " " }, { "face": { "fg": "blue", "bg": "default", "underline": "default", "attributes": [] }, "contents": "1 sel" }, { "face": { "fg": "default", "bg": "default", "underline": "default", "attributes": [] }, "contents": " - client0@[kak-tests]" }], { "fg": "cyan", "bg": "default", "underline": "default", "attributes": [] }] }
          + { "jsonrpc": "2.0", "method": "draw_status", "params": [[{ "face": { "fg": "black", "bg": "yellow", "underline": "default", "attributes": [] }, "contents": "2017-07-13 A U Thor \"Don't break on single quotes or unbalanced {\"" }], [{ "face": { "fg": "default", "bg": "default", "underline": "default", "attributes": [] }, "contents": "*git* 13:2 " }, { "face": { "fg": "black", "bg": "yellow", "underline": "default", "attributes": [] }, "contents": "[scratch]" }, { "face": { "fg": "default", "bg": "default", "underline": "default", "attributes": [] }, "contents": " " }, { "face": { "fg": "blue", "bg": "default", "underline": "default", "attributes": [] }, "contents": "1 sel" }, { "face": { "fg": "default", "bg": "default", "underline": "default", "attributes": [] }, "contents": " - client0@[kak-tests]" }], { "fg": "cyan", "bg": "default", "underline": "default", "attributes": [] }] }
```

Narrowing this down, you can see that the difference is the date `2017-07-14` being expected, but the date `2017-07-13` being returned.

This is likely due to the environment for the test being interpreted differently than expected:

```
export GIT_AUTHOR_DATE="1500000000 -0500"
export GIT_COMMITTER_DATE="1500000000 -0500"
```

### Expectations

Test should pass.

### Additional information

I do have my default shell set to `fish`, and I have a custom `/etc/gitconfig` fpile, but neither of these should be affecting the result. The tests are explicitly set with a shebang of `/bin/sh` and the `gitconfig` I've set only includes aliases and not any time zone settings.

My current git version is 2.48.1, in case it's something that changed in a newer version of git.

**Comment by krobelus** [comment]
Surprisingly, these two commands show different commit times:

	git blame README.asciidoc
	kak -e 'git blame' README.asciidoc

This is because git shows times as of the original time zone (of the
author/committer).  Our blame integration uses the current local time.

- blame-jump displays the date in the status line of a git-show buffer
  This date may be inconsistent with the buffer's "Date:" header,
  so this seems surprising. Fix that. This fixes a test in some
  time zones.
- Unlike "git blame", our ":git blame" does not display time zone
  info by default. So, the conversion to localtime might make sense.
  I don't really have an opinion on this. Change it too I guess,
  since the current behavior might not have been intended.

Fixes #5285
---
 rc/tools/git.kak                         | 16 ++++++++++++++--
 test/tools/git/blame-jump-message/script |  2 +-
 2 files changed, 15 insertions(+), 3 deletions(-)

diff --git a/rc/tools/git.kak b/rc/tools/git.kak
index cf2f73195d..5b46d2d8dd 100644
--- a/rc/tools/git.kak
+++ b/rc/tools/git.kak
@@ -308,6 +308,7 @@ define-command -params 1.. \
                       set-option buffer=$kak_bufname git_blame ''
                   }" | kak -p ${kak_session}
             if ! stderr=$({ git blame --incremental "$@" <${blame_stdin} | perl -wne '
+                  BEGIN {
                   use POSIX qw(strftime);
                   sub quote {
                       my $SQ = "'\''";
@@ -341,6 +342,7 @@ define-command -params 1.. \
                       $raw_blame = "";
                       $last_sent = $now;
                   }
+                  }
                   $raw_blame .= $_;
                   chomp;
                   if (m/^([0-9a-f]+) ([0-9]+) ([0-9]+) ([0-9]+)/) {
@@ -356,7 +358,12 @@ define-command -params 1.. \
                       $authors{$sha} = substr($_,7);
                       $authors{$sha} = "Not Committed Yet" if $authors{$sha} eq "External file (--contents)";
                   }
-                  if (m/^author-time ([0-9]*)/) { $dates{$sha} = strftime("%F %T", localtime $1) }
+                  if (m/^author-time ([0-9]*)/) { $author_time = $1; }
+                  if (m/^author-tz ([+-])(\d\d)/) {
+                      my $sign = $1 eq "+" ? "-" : "+";
+                      local $ENV{"TZ"} = "UTC${sign}$2";
+                      $dates{$sha} = strftime("%F %T", localtime $author_time);
+                  }
                   END { send_flags(1); }'
             } 2>&1); then
                 escape2() { printf %s "$*" | sed "s/'/''''/g"; }
@@ -683,7 +690,12 @@ define-command -params 1.. \
             }
             if (m/^filename /) { $old_filenames{$sha} = substr($_,9) }
             if (m/^author /) { $authors{$sha} = substr($_,7) }
-            if (m/^author-time ([0-9]*)/) { $dates{$sha} = strftime("%F", localtime $1) }
+            if (m/^author-time ([0-9]*)/) { $author_time = $1; }
+            if (m/^author-tz ([+-])(\d\d)/) {
+                my $sign = $1 eq "+" ? "-" : "+";
+                local $ENV{"TZ"} = "UTC${sign}$2";
+                $dates{$sha} = strftime("%F", localtime $author_time);
+            }
             if (m/^summary /) { $summaries{$sha} = substr($_,8) }
             END {
                 if ***@***.***_index and not defined $target_in_blame) {
diff --git a/test/tools/git/blame-jump-message/script b/test/tools/git/blame-jump-message/script
index 92b1f67087..daf5e48c21 100644
--- a/test/tools/git/blame-jump-message/script
+++ b/test/tools/git/blame-jump-message/script
@@ -1,5 +1,5 @@
 expected_subject=$(cat <<'EOF'
-2017-07-14 A U Thor "Don't break on single quotes or unbalanced {"
+2017-07-13 A U Thor "Don't break on single quotes or unbalanced {"
 EOF
 )
 expected_subject_json=\"$(printf '%s' "$expected_subject" | sed 's/"/\\"/g')\"

**Comment by krobelus** [comment]
I cc-ed my [proposed
fix](https://lists.sr.ht/~mawww/kakoune/patches/57137) here; github seems
to drop the subject line though, so this is weird.

> I have a custom `/etc/gitconfig`

we ignore that via GIT_CONFIG_NOSYSTEM=true

**Comment by krobelus** [comment]
Applied, Thanks.

**Comment by mawww** [comment]
This is fixed now, right ?

**Comment by clarfonthey** [comment]
The linked patch doesn't seem to have been merged yet; it's still failing to pass the tests on the latest commit.

**Comment by mawww** [comment]
Hum, I thought I did, but yeah its not in the log, my mistake, will apply it again.
